<table>
		<thead>
			<tr>
				<th>Luke</th>
				<th>Michael</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>Image</td>
				<td>&nbsp;</td>
				<td>&nbsp;image</td>
			</tr>
			<tr>
				<td><span style="font-style: normal; font-weight: 400;">About&nbsp;</span><br></td>
				<td>&nbsp;</td>
				<td>&nbsp;about</td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>
		</tbody>
	</table>